PRINT 'Backing up [{{DATABASE}}]'

BACKUP DATABASE [{{DATABASE}}] TO
	DISK = N'{{SAVE_BAK_AS_PATH}}' 
	WITH 
 		 NOFORMAT
		,INIT
		,NAME = N'{{BACKUP_SET_NAME}}'
		,SKIP
		,NOREWIND
		,NOUNLOAD
		,COMPRESSION
		,STATS = 10
GO
