//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MockDebt.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SavingsUnit
    {
        public int SavingsUnitId { get; set; }
        public int UserId { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public string ItemLink { get; set; }
        public string Notes { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual User User { get; set; }
    }
}
