//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LotteryWcfService {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class CachedValues : global::System.Configuration.ApplicationSettingsBase {
        
        private static CachedValues defaultInstance = ((CachedValues)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new CachedValues())));
        
        public static CachedValues Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime LastCheckedTimeStamp {
            get {
                return ((global::System.DateTime)(this["LastCheckedTimeStamp"]));
            }
            set {
                this["LastCheckedTimeStamp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastPulledLottoNumber {
            get {
                return ((string)(this["LastPulledLottoNumber"]));
            }
            set {
                this["LastPulledLottoNumber"] = value;
            }
        }
    }
}
