//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskListPoolLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskGroupLink
    {
        public System.Guid TaskGroupLinkId { get; set; }
        public int TaskGroupId { get; set; }
        public int TaskId { get; set; }
    
        public virtual Task Task { get; set; }
        public virtual TaskGroup TaskGroup { get; set; }
    }
}
